### ISSUE TITLE
Removing and adding a GIF results in AssertionError when attempting to generate

### ISSUE THREAD

**Issue by MegaScience** [LonicaMewinsky/gif2gif#2] opened 2023-02-19 14:51 UTC
If I remove a GIF from the gif2gif UI using the `x` button and put a GIF in, attempting to generate images always immediately fails with the following `AssertionError`. This persists even if the GIF is removed and gif2gif script disabled. Reloading the webpage makes the error stop occuring, so I assume it's an error with how data of the inputted GIF is read and conveyed to the browser; Thus, it could be a WebUI issue, though maybe there's a way for gif2gif to implement a fix to still allow generation even if it, itself, can't run. I am using Firefox 110.0 (64-bit), though I just tested and it also occurs with Chrome.
```
Traceback (most recent call last):
  File "...\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "...\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "...\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File ...\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1488, in preprocess
    assert isinstance(x, dict)
AssertionError
```

**Comment by LonicaMewinsky** [comment] 2023-02-19 22:13
@MegaScience unfortunately I am not able to reproduce this problem on the current commit. Are you using any other extensions that could be interacting with it? (ControlNet, Animator, etc?)

**Comment by MegaScience** [comment] 2023-02-20 17:10
I did have ControlNet enabled. However, I just disabled all non-built-in extensions except gif2gif, applied, and completely restarted my UI (closing the cmd prompt and refreshed the page), and the issue is still occurring. I am on the latest commit of the WebUI (https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8).

What I did just discover is it only happens if you remove and add back the exact same GIF that was already in the UI. Choosing a different GIF first clears the issue. (I had significant artifacts in the first frame, which I attributed to that the preview when initially putting a GIF in was very low quality. I noticed removing it and putting it back made the preview look better, though it also lead to the `AssertionError`.)

**Summary:** It happens if you place a GIF, remove it, then place that same exact GIF back in and attempt to generate. If you remove it, place a different GIF in, remove that, then put the original back in, it works.

**Comment by LonicaMewinsky** [comment] 2023-02-20 17:18
Got it, thanks, was able to reproduce using the same image. I'll get it fixed up. :)

**Comment by LonicaMewinsky** [comment] 2023-02-23 19:18
Just updated. Should be good to go now. Unfortunately I'll have to leave the drag/drop functionality out until I can find a way to use it without these types of problems.

Mind updating and giving it a try?

**Comment by MegaScience** [comment] 2023-02-23 19:50
Oddly enough, that still resulted in an AssertionError when selecting the same GIF. That's actually perplexing. Perhaps it's a general gradio bug? Hmm... Have to figure out the path all this takes.

**Comment by LonicaMewinsky** [comment] 2023-03-03 16:17
Did a significant re-work on how images are uploaded and assigned to img2img. I suspect this is resolved with today's update. Mind giving it a try? If it still doesn't work, mind sharing the gif in question?

**Comment by MegaScience** [comment] 2023-03-04 13:30
Of course it doesn't work exactly the same, but the information is there and can be accessed, which is good. Curious if there can be a change on the WebUI end to accommodate this kind of GIF metadata directly.

**Closed** 2023-03-06 18:01 UTC
Labels: bug
